name: Publish PowerShell Module

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to PowerShell Gallery
      env:
        PS_GALLERY_KEY: ${{ secrets.PS_GALLERY_KEY }}
      shell: pwsh
      run: |
        Write-Host -Object 'Publishing module (Office365-Scoutnet-synk) to PowerShell Gallery'
        Publish-Module -Path Office365-Scoutnet-synk -NuGetApiKey $env:PS_GALLERY_KEY -Verbose -ErrorAction "Stop"
        Write-Host -Object 'Finished publishing module to PowerShell Gallery'
