name: Release handling

on:
  push:
    tags:
      - "v*"

jobs:
  generate-release:
    name: "Generate release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Build release package"
        run: |
          zip -r Office365-Scoutnet-synk.zip Office365-Scoutnet-synk

      - name: Install needed modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module MSOnline -ErrorAction Stop

      - name: Test-ModuleManifest
        shell: pwsh
        run: |
          Test-ModuleManifest Office365-Scoutnet-synk/Office365-Scoutnet-synk.psd1 -ErrorAction Stop

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            MaillistSynk.ps1
            MaillistSynk_local.ps1
            Office365-Scoutnet-synk.zip

      - name: "Publish to PowerShell Gallery"
        env:
          PS_GALLERY_KEY: ${{ secrets.PS_GALLERY_KEY }}
        shell: pwsh
        run: |
          Write-Host -Object 'Publishing module (Office365-Scoutnet-synk) to PowerShell Gallery'
          Publish-Module -Path Office365-Scoutnet-synk -NuGetApiKey $env:PS_GALLERY_KEY -Verbose -ErrorAction "Stop"
          Write-Host -Object 'Finished publishing module to PowerShell Gallery'
